on: ["push","pull_request"]

name: build

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          version: 14.x
      - run: npm install
      - run: npm run coverage

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: tintef/nyc-reporter-action
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPORTER: 'text' # defaults to 'text-summary'
