on: ["push","pull_request"]

name: build

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 20.x
      - run: npm install
      - run: npm run test
